[project]
name = "languagemodeling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipykernel>=6.29.5",
    "pip>=25.0.1",
    "torch>=2.7.0",
]
